### ISSUE TITLE
Server crashes after player joins

### ISSUE THREAD

**Issue by blha303** [ddevault/PartyCraft#16]
I join, i spawn underneath a bedrock layer. I opped myself from console and used '/gamemode 1' in the game, then started flying up. After maybe 30 seconds, though, the server crashed with this error:

```
C:\Users\Steven\workspace\PartyCraft\PartyCraft\bin\Debug>PartyCraft.exe
Use /stop to kill the server.

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Threading.Monitor.Enter(Object obj, Boolean& lockTaken)
   at Craft.Net.Anvil.Region.Save() in c:\Users\Steven\workspace\PartyCraft
      \externals\Craft.Net\source\Craft.Net.Anvil\Region.cs:line 205
   at Craft.Net.Anvil.World.Save() in c:\Users\Steven\workspace\PartyCraft
      \externals\Craft.Net\source\Craft.Net.Anvil\World.cs:line 175
   at Craft.Net.Anvil.Level.Save() in c:\Users\Steven\workspace\PartyCraft
      \externals\Craft.Net\source\Craft.Net.Anvil\Level.cs:line 278
   at PartyCraft.Server.<Start>b__0(Object o) in c:\Users\Steven\workspace\PartyCraft
      \PartyCraft\Server.cs:line 57
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext 
      executionContext, ContextCallback callback, Object state, Boolean 
      preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext 
      executionContext, ContextCallback callback, Object state, Boolean 
      preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()
```

Windows 7, 3GB ram, running minecraft on same machine as server, compiled with Xamarin Studio 4.0.12 from http://monodevelop.com

**Comment by ddevault** [comment]
PartyCraft is on the eve of a huge refactoring, and problems like this will probably go away. I just shoved in a few quick patches to get it working after the huge Craft.Net refactoring of last month.

I suggest just playing around with the Craft.Net TestServer until that time, unless you'd like to fix this problem yourself and submit a pull request (which you're more than welcome to do).

**Comment by jessestricker** [comment]
I found a fix, should I submit a PR or will you fix it as part of the refactoring?

**Comment by ddevault** [comment]
Is the fix in Craft.Net or PartyCraft?

**Comment by jessestricker** [comment]
Craft net

**Comment by ddevault** [comment]
Then I'd suggest submitting a pull request to Craft.Net.
